apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instvote
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-instavote
  url: https://github.com/solomon-n/instavote.git